version: '3.1'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: eventor-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.1.248" 
      KAFKA_CREATE_TOPICS: "business_entity:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
 
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: eventor-zookeeper
    ports:
      - 2181:2181
